import React, { useState } from 'react';
import { X, Plus, Sparkles, Edit, Trash2, Save, RefreshCw, Wand2, Download, Upload } from 'lucide-react';
import { Product, BlogPost } from '../types';
import { CATEGORIES } from '../data/mockData';

interface CmsAdminModalProps {
  isOpen: boolean;
  onClose: () => void;
  products: Product[];
  blogPosts: BlogPost[];
  onAddProduct: (product: Product) => void;
  onAddBlogPost: (post: BlogPost) => void;
  onDeleteProduct: (id: string) => void;
  onDeleteBlogPost: (id: string) => void;
  onResetData: () => void;
}

export const CmsAdminModal: React.FC<CmsAdminModalProps> = ({
  isOpen,
  onClose,
  products,
  blogPosts,
  onAddProduct,
  onAddBlogPost,
  onDeleteProduct,
  onDeleteBlogPost,
  onResetData
}) => {
  if (!isOpen) return null;

  const [activeTab, setActiveTab] = useState<'products' | 'blogs' | 'ai-generator'>('products');
  
  // Product Form State
  const [newProd, setNewProd] = useState<Partial<Product>>({
    title: '',
    category: 'Home Decor',
    price: '$29.99',
    image: 'https://images.unsplash.com/photo-1612196808214-b7e239e5f6b7?auto=format&fit=crop&w=800&q=80',
    shortDescription: '',
    fullReview: '',
    aliexpressUrl: 'https://www.aliexpress.com?tag=glownest-20',
    pros: ['Great design', 'Durable material'],
    cons: ['Limited stock'],
    rating: 4.8,
    reviewCount: 150,
    isChoice: true,
    isTrending: true
  });

  // AI Generator State
  const [aiType, setAiType] = useState<'blog' | 'product'>('blog');
  const [aiTopic, setAiTopic] = useState('');
  const [aiCategory, setAiCategory] = useState('Beauty & Self-Care');
  const [aiLoading, setAiLoading] = useState(false);
  const [aiStatusMessage, setAiStatusMessage] = useState('');

  const handleCreateProduct = (e: React.FormEvent) => {
    e.preventDefault();
    if (!newProd.title) return;

    const catObj = CATEGORIES.find(c => c.name === newProd.category) || CATEGORIES[0];
    const product: Product = {
      id: `prod-${Date.now()}`,
      title: newProd.title || 'Untitled AliExpress Product',
      slug: (newProd.title || 'product').toLowerCase().replace(/[^a-z0-9]+/g, '-'),
      category: catObj.name,
      categorySlug: catObj.slug,
      image: newProd.image || 'https://images.unsplash.com/photo-1612196808214-b7e239e5f6b7?auto=format&fit=crop&w=800&q=80',
      price: newProd.price || '$29.99',
      originalPrice: newProd.originalPrice,
      rating: newProd.rating || 4.8,
      reviewCount: newProd.reviewCount || 100,
      shortDescription: newProd.shortDescription || 'Aesthetic luxury find available on AliExpress.',
      fullReview: newProd.fullReview || 'Detailed hands-on testing review from GlowNest editors.',
      pros: newProd.pros || ['High quality', 'Elegant aesthetic'],
      cons: newProd.cons || ['Standard shipping'],
      aliexpressUrl: newProd.aliexpressUrl || newProd.amazonUrl || 'https://www.aliexpress.com',
      isTrending: newProd.isTrending ?? true,
      isChoice: newProd.isChoice ?? true,
      tags: [catObj.name, 'AliExpress Find'],
      updatedDate: new Date().toISOString().split('T')[0]
    };

    onAddProduct(product);
    alert('✨ New AliExpress Product successfully added to GlowNest catalog!');
    setNewProd({
      title: '',
      category: 'Home Decor',
      price: '$29.99',
      image: 'https://images.unsplash.com/photo-1612196808214-b7e239e5f6b7?auto=format&fit=crop&w=800&q=80',
      shortDescription: '',
      fullReview: '',
      aliexpressUrl: 'https://www.aliexpress.com'
    });
  };

  const handleGenerateAi = async () => {
    if (!aiTopic.trim()) {
      alert('Please enter a topic or product name for AI generation.');
      return;
    }

    setAiLoading(true);
    setAiStatusMessage('Connecting to Gemini AI content generator...');

    try {
      const res = await fetch('/api/ai/generate', {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({
          type: aiType,
          topic: aiTopic,
          category: aiCategory
        })
      });

      const data = await res.json();

      if (data.success && data.data) {
        if (aiType === 'blog') {
          const generatedPost: BlogPost = {
            id: `post-${Date.now()}`,
            title: data.data.title || aiTopic,
            slug: (data.data.title || aiTopic).toLowerCase().replace(/[^a-z0-9]+/g, '-'),
            category: aiCategory,
            excerpt: data.data.excerpt || 'AI generated article summary for GlowNest readers.',
            content: data.data.content || 'Content generated by Gemini AI.',
            image: 'https://images.unsplash.com/photo-1618221195710-dd6b41faaea6?auto=format&fit=crop&w=800&q=80',
            author: {
              name: 'AI Editorial Assistant',
              avatar: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?auto=format&fit=crop&w=200&q=80',
              role: 'GlowNest Content Engine'
            },
            publishedAt: new Date().toISOString().split('T')[0],
            readTime: data.data.readTime || '5 min read',
            relatedProductIds: [products[0]?.id || 'prod-1']
          };
          onAddBlogPost(generatedPost);
          alert('🎉 Gemini AI successfully generated and published a new blog post!');
        } else {
          const generatedProduct: Product = {
            id: `prod-${Date.now()}`,
            title: data.data.title || aiTopic,
            slug: (data.data.title || aiTopic).toLowerCase().replace(/[^a-z0-9]+/g, '-'),
            category: aiCategory,
            categorySlug: CATEGORIES.find(c => c.name === aiCategory)?.slug || 'home-decor',
            image: 'https://images.unsplash.com/photo-1596462502278-27bfdc403348?auto=format&fit=crop&w=800&q=80',
            price: data.data.price || '$29.99',
            rating: 4.8,
            reviewCount: 210,
            shortDescription: data.data.shortDescription || 'Generated review find.',
            fullReview: data.data.fullReview || 'Detailed hands-on evaluation.',
            pros: data.data.pros || ['Elevated aesthetic', 'High build quality'],
            cons: data.data.cons || ['May require care during cleaning'],
            aliexpressUrl: 'https://www.aliexpress.com',
            isTrending: true,
            isChoice: true,
            tags: data.data.tags || [aiCategory, 'AliExpress Find'],
            updatedDate: new Date().toISOString().split('T')[0]
          };
          onAddProduct(generatedProduct);
          alert('🎉 Gemini AI successfully generated a new Product Review!');
        }
        setAiTopic('');
      } else {
        alert(`Gemini AI Notice: ${data.error || 'Server needs GEMINI_API_KEY set in secrets. Using local template.'}`);
      }
    } catch (err) {
      console.error(err);
      alert('Unable to reach backend AI service. Ensure dev server is active.');
    } finally {
      setAiLoading(false);
      setAiStatusMessage('');
    }
  };

  return (
    <div className="fixed inset-0 z-50 flex items-center justify-center p-4 sm:p-6 overflow-y-auto bg-[#000000]/80 backdrop-blur-sm animate-in fade-in">
      <div className="bg-[#1C1C20] rounded-3xl max-w-4xl w-full max-h-[90vh] overflow-y-auto shadow-2xl border border-[#27272A] relative my-auto text-[#F7F3EF]">
        
        {/* Header */}
        <div className="sticky top-0 z-20 bg-[#18181C] text-[#F7F3EF] border-b border-[#27272A] px-6 py-4 flex items-center justify-between">
          <div className="flex items-center gap-2">
            <Sparkles className="w-5 h-5 text-[#C8A96A]" />
            <h2 className="font-serif text-lg font-bold">GlowNest CMS Content Manager</h2>
          </div>
          <button onClick={onClose} className="p-1.5 rounded-full hover:bg-[#27272A] text-[#A1A1AA] hover:text-[#F7F3EF]">
            <X className="w-5 h-5" />
          </button>
        </div>

        <div className="p-6 sm:p-8 space-y-6">
          
          {/* Navigation Tabs */}
          <div className="flex items-center gap-2 border-b border-[#27272A] pb-3">
            <button
              onClick={() => setActiveTab('products')}
              className={`px-4 py-2 rounded-full text-xs font-bold transition-all ${
                activeTab === 'products' ? 'bg-[#C8A96A] text-[#121214]' : 'bg-[#18181C] text-[#A1A1AA] hover:text-[#F7F3EF]'
              }`}
            >
              Manage Products ({products.length})
            </button>
            <button
              onClick={() => setActiveTab('blogs')}
              className={`px-4 py-2 rounded-full text-xs font-bold transition-all ${
                activeTab === 'blogs' ? 'bg-[#C8A96A] text-[#121214]' : 'bg-[#18181C] text-[#A1A1AA] hover:text-[#F7F3EF]'
              }`}
            >
              Manage Blog Articles ({blogPosts.length})
            </button>
            <button
              onClick={() => setActiveTab('ai-generator')}
              className={`px-4 py-2 rounded-full text-xs font-bold transition-all flex items-center gap-1.5 ${
                activeTab === 'ai-generator' ? 'bg-[#EFB7C8] text-[#121214]' : 'bg-[#18181C] text-[#EFB7C8] border border-[#27272A]'
              }`}
            >
              <Wand2 className="w-3.5 h-3.5" />
              <span>AI Gemini Writer</span>
            </button>
          </div>

          {/* TAB 1: Add / Edit Products */}
          {activeTab === 'products' && (
            <div className="space-y-8">
              
              {/* Add Product Form */}
              <form onSubmit={handleCreateProduct} className="p-6 rounded-2xl bg-[#18181C] border border-[#27272A] space-y-4">
                <h3 className="font-serif text-base font-bold text-[#F7F3EF] flex items-center gap-2">
                  <Plus className="w-4 h-4 text-[#C8A96A]" /> Add New AliExpress Product
                </h3>

                <div className="grid grid-cols-1 sm:grid-cols-2 gap-4 text-xs">
                  <div>
                    <label className="block font-semibold text-[#A1A1AA] mb-1">Product Title</label>
                    <input
                      type="text"
                      required
                      placeholder="e.g. Minimalist Ceramic Incense Burner"
                      value={newProd.title}
                      onChange={(e) => setNewProd({ ...newProd, title: e.target.value })}
                      className="w-full bg-[#121214] p-2.5 rounded-xl border border-[#27272A] text-[#F7F3EF] focus:border-[#C8A96A] outline-hidden"
                    />
                  </div>

                  <div>
                    <label className="block font-semibold text-[#A1A1AA] mb-1">Category</label>
                    <select
                      value={newProd.category}
                      onChange={(e) => setNewProd({ ...newProd, category: e.target.value })}
                      className="w-full bg-[#121214] p-2.5 rounded-xl border border-[#27272A] text-[#F7F3EF] focus:border-[#C8A96A] outline-hidden"
                    >
                      {CATEGORIES.map(c => <option key={c.id}>{c.name}</option>)}
                    </select>
                  </div>

                  <div>
                    <label className="block font-semibold text-[#A1A1AA] mb-1">Price</label>
                    <input
                      type="text"
                      placeholder="$29.99"
                      value={newProd.price}
                      onChange={(e) => setNewProd({ ...newProd, price: e.target.value })}
                      className="w-full bg-[#121214] p-2.5 rounded-xl border border-[#27272A] text-[#F7F3EF] focus:border-[#C8A96A] outline-hidden"
                    />
                  </div>

                  <div>
                    <label className="block font-semibold text-[#A1A1AA] mb-1">Image URL</label>
                    <input
                      type="text"
                      placeholder="https://images.unsplash.com/..."
                      value={newProd.image}
                      onChange={(e) => setNewProd({ ...newProd, image: e.target.value })}
                      className="w-full bg-[#121214] p-2.5 rounded-xl border border-[#27272A] text-[#F7F3EF] focus:border-[#C8A96A] outline-hidden"
                    />
                  </div>
                </div>

                <div>
                  <label className="block font-semibold text-[#A1A1AA] text-xs mb-1">AliExpress Affiliate Link</label>
                  <input
                    type="text"
                    placeholder="https://www.aliexpress.com/item/1005001234567.html"
                    value={newProd.aliexpressUrl || newProd.amazonUrl || ''}
                    onChange={(e) => setNewProd({ ...newProd, aliexpressUrl: e.target.value })}
                    className="w-full bg-[#121214] p-2.5 rounded-xl border border-[#27272A] text-[#F7F3EF] focus:border-[#C8A96A] text-xs outline-hidden"
                  />
                </div>

                <div>
                  <label className="block font-semibold text-[#A1A1AA] text-xs mb-1">Short Description</label>
                  <textarea
                    rows={2}
                    placeholder="Brief 2-sentence summary..."
                    value={newProd.shortDescription}
                    onChange={(e) => setNewProd({ ...newProd, shortDescription: e.target.value })}
                    className="w-full bg-[#121214] p-2.5 rounded-xl border border-[#27272A] text-[#F7F3EF] focus:border-[#C8A96A] text-xs outline-hidden"
                  />
                </div>

                <button
                  type="submit"
                  className="w-full py-3 rounded-full bg-[#C8A96A] hover:bg-[#EFB7C8] text-[#121214] text-xs font-bold transition-colors shadow-md"
                >
                  Publish Product to Website
                </button>
              </form>

              {/* Product List Table */}
              <div className="space-y-3">
                <h3 className="font-serif text-base font-bold text-[#F7F3EF]">Current Products ({products.length})</h3>
                <div className="space-y-2 max-h-60 overflow-y-auto">
                  {products.map((p) => (
                    <div key={p.id} className="p-3 bg-[#18181C] rounded-xl border border-[#27272A] flex items-center justify-between gap-3 text-xs">
                      <div className="flex items-center gap-3 min-w-0">
                        <img src={p.image} alt="" className="w-10 h-10 rounded-lg object-cover" referrerPolicy="no-referrer" />
                        <div className="min-w-0">
                          <p className="font-bold text-[#F7F3EF] truncate">{p.title}</p>
                          <p className="text-[10px] text-[#C8A96A]">{p.price} • {p.category}</p>
                        </div>
                      </div>
                      <button
                        onClick={() => onDeleteProduct(p.id)}
                        className="p-2 rounded-lg text-rose-400 hover:bg-rose-950/40"
                        title="Delete product"
                      >
                        <Trash2 className="w-4 h-4" />
                      </button>
                    </div>
                  ))}
                </div>
              </div>

            </div>
          )}

          {/* TAB 2: Manage Blogs */}
          {activeTab === 'blogs' && (
            <div className="space-y-4">
              <h3 className="font-serif text-base font-bold text-[#F7F3EF]">Published Blog Posts ({blogPosts.length})</h3>
              <div className="space-y-3">
                {blogPosts.map((post) => (
                  <div key={post.id} className="p-4 bg-[#18181C] rounded-2xl border border-[#27272A] flex items-center justify-between gap-4">
                    <div className="flex items-center gap-3 min-w-0">
                      <img src={post.image} alt="" className="w-12 h-12 rounded-xl object-cover" referrerPolicy="no-referrer" />
                      <div className="min-w-0">
                        <p className="font-serif font-bold text-sm text-[#F7F3EF] truncate">{post.title}</p>
                        <p className="text-xs text-[#A1A1AA]">{post.category} • {post.readTime}</p>
                      </div>
                    </div>
                    <button
                      onClick={() => onDeleteBlogPost(post.id)}
                      className="p-2 rounded-lg text-rose-400 hover:bg-rose-950/40"
                      title="Delete post"
                    >
                      <Trash2 className="w-4 h-4" />
                    </button>
                  </div>
                ))}
              </div>
            </div>
          )}

          {/* TAB 3: AI Gemini Content Generator */}
          {activeTab === 'ai-generator' && (
            <div className="p-6 rounded-2xl bg-[#18181C] border border-[#27272A] space-y-6">
              <div className="flex items-center gap-2">
                <Wand2 className="w-5 h-5 text-[#C8A96A]" />
                <h3 className="font-serif text-lg font-bold text-[#F7F3EF]">Gemini AI Content Generator</h3>
              </div>

              <p className="text-xs text-[#A1A1AA] font-light">
                Use Gemini AI to instantly generate new blog posts or comprehensive product reviews formatted for GlowNest.
              </p>

              <div className="space-y-4 text-xs">
                <div>
                  <label className="block font-semibold text-[#A1A1AA] mb-1">Generation Type</label>
                  <div className="flex gap-4 text-[#F7F3EF]">
                    <label className="flex items-center gap-2 cursor-pointer">
                      <input
                        type="radio"
                        name="aitype"
                        checked={aiType === 'blog'}
                        onChange={() => setAiType('blog')}
                      />
                      <span>Blog Article</span>
                    </label>
                    <label className="flex items-center gap-2 cursor-pointer">
                      <input
                        type="radio"
                        name="aitype"
                        checked={aiType === 'product'}
                        onChange={() => setAiType('product')}
                      />
                      <span>Product Review</span>
                    </label>
                  </div>
                </div>

                <div>
                  <label className="block font-semibold text-[#A1A1AA] mb-1">Topic / Product Name</label>
                  <input
                    type="text"
                    placeholder="e.g. 10 Best Aesthetic Matcha Accessories on AliExpress"
                    value={aiTopic}
                    onChange={(e) => setAiTopic(e.target.value)}
                    className="w-full bg-[#121214] p-3 rounded-xl border border-[#27272A] text-[#F7F3EF] focus:border-[#C8A96A] outline-hidden"
                  />
                </div>

                <div>
                  <label className="block font-semibold text-[#A1A1AA] mb-1">Category</label>
                  <select
                    value={aiCategory}
                    onChange={(e) => setAiCategory(e.target.value)}
                    className="w-full bg-[#121214] p-3 rounded-xl border border-[#27272A] text-[#F7F3EF] focus:border-[#C8A96A] outline-hidden"
                  >
                    {CATEGORIES.map(c => <option key={c.id}>{c.name}</option>)}
                  </select>
                </div>

                <button
                  onClick={handleGenerateAi}
                  disabled={aiLoading}
                  className="w-full py-3.5 rounded-full bg-[#C8A96A] hover:bg-[#EFB7C8] text-[#121214] font-bold text-xs transition-colors flex items-center justify-center gap-2 shadow-md"
                >
                  {aiLoading ? (
                    <>
                      <RefreshCw className="w-4 h-4 animate-spin text-[#121214]" />
                      <span>Generating with Gemini AI...</span>
                    </>
                  ) : (
                    <>
                      <Sparkles className="w-4 h-4 text-[#121214]" />
                      <span>Generate & Auto-Publish Content</span>
                    </>
                  )}
                </button>

                {aiStatusMessage && (
                  <p className="text-[11px] text-[#C8A96A] text-center font-medium animate-pulse">{aiStatusMessage}</p>
                )}
              </div>
            </div>
          )}

          {/* Bottom Reset Button */}
          <div className="pt-4 border-t border-[#27272A] flex justify-between items-center text-xs">
            <span className="text-[#A1A1AA]">Local Storage Active</span>
            <button
              onClick={() => {
                if (confirm('Reset site data back to initial default items?')) {
                  onResetData();
                  alert('Site data reset to defaults.');
                }
              }}
              className="text-rose-400 hover:underline font-medium"
            >
              Reset Default Data
            </button>
          </div>

        </div>

      </div>
    </div>
  );
};
